spring:
  application:
    name: tixly
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: changemeinprod!
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/tixly
